spring.security.user.password=test_password
spring.data.mongodb.uri=${MONGO_CONNECTION_STRING}
jwt.secret=${JWT_SECRET}

# Change the OpenAPI JSON endpoint path (default is /v3/api-docs)
springdoc.api-docs.path=/v3/api-docs

# Change the Swagger UI path (default is /swagger-ui/index.html)
springdoc.swagger-ui.path=/swagger-ui.html

# Explicitly enable Swagger UI (usually enabled by default)
springdoc.swagger-ui.enabled=true

