### QWEN
qwen.api.key=${QWEN_API_KEY}
qwen.base.url=${QWEN_BASE_URL}

### Gemini
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=${GEMINI_BASE_URL}

spring.security.user.password=test_password
spring.data.mongodb.uri=${MONGO_CONNECTION_STRING}
jwt.secret=${JWT_SECRET}

# Change the OpenAPI JSON endpoint path (default is /v3/api-docs)
springdoc.api-docs.path=/v3/api-docs

# Change the Swagger UI path (default is /swagger-ui/index.html)
springdoc.swagger-ui.path=/swagger-ui.html

# Explicitly enable Swagger UI (usually enabled by default)
springdoc.swagger-ui.enabled=true

# Aws
aws.access.key.id=${AWS_ACCESS_KEY}
aws.secret.key=${AWS_SECRET_KEY}

# Vision
google.cloud.vision.credentials.location=${GOOGLE_APPLICATION_CREDENTIALS}

